server:
  port: 8081

  spring:
    datasource:
      driverClassName: org.h2.Driver
      url: jdbc:h2:tcp://localhost/~/CityRentalSystem
      username: fijez
      password: forAccenture
      hikari:
        maxLifetimeL: 3600
        maximumPoolSize: 1
        connection-timeout: 10000

    jpa:
      open-in-view: false
        liquibase:

          sequrity:
            jst-secret: secret
